### ISSUE TITLE
Implement Profile Scope

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/underware#21]
Much like the platform scope (see #17) enhancement this would add arbitrary 'profiles' that can be used to override configuration data. For example, a network layout profile whichat will enable/disable multiple networks based on the choice (`simple`, `management`, `management_and_ib`). 

In terms of where in the hierarchy `profiles` should sit I think it should be between `domain` and `group` to provide a domain-level network setup (following the example above) but allowing for group overrides. Or perhaps profiles are something that can be set at multiple scope levels.

**Comment by bobwhitelock** [comment]
Going to see if we can do this with content for now (conditional questions based on type of node you choose) but may implement later.

**Comment by bobwhitelock** [comment]
Thinking about things some more: even if this isn't possible to implement as content as things stand (e.g. we have many different optional profiles that we want to use in different combinations, and so the combinations become unmanageable), maybe this is still just a special case of https://github.com/alces-software/underware/issues/4.

Essentially, once #4 is handled, we might be able to handle this by having a question something like this defined in `configure.yaml`:
```yaml
  - &profiles
    identifier: profiles
    question: 'Choose a profile to enable'
    loop: true
    choices:
      - management
      - ib
      - gpu
      - stu
      [ etc. ]
```

This should then collect all the entered profiles up into an array (until the user doesn't enter another one), and then within configs/templates we should be able to have conditional sections like this:
```erb
<% if answers.profiles.include? :stu %>
  # Enable Stu's special config for a node.
<% end %>
```

Let me know if this sounds like it would be sufficient or if there would still be something missing from this.  Also feel free to close this if resolving #4 + content changes would be sufficient, or leave it open if not (or if you just want this as a reminder to add the content once #4 has been resolved :slightly_smiling_face:).

**Comment by ColonelPanicks** [comment]
@bobwhitelock I like where you're coming from with that but it feels to me like `profiles` refer to additional configuration outside of the domain/group/node hierarchy but aren't restricted to a single question. 

As I see it, there could be multiple questions for different types of profile:
```yaml
- &network_layout
  identifier: network_layout
  type: profile
  question: 'Network layout to use'
  choices:
    - simple_net
    - simple_management_net
    - simple_management_ib_net
  default: 'simple_net'

- &network_range
  identifier: network_range
  type: profile
  question: 'IP ranges to use for networks'
  choices:
    - 10.0.0.0
    - 172.16.0.0
    - 192.168.0.0
  default: '10.0.0.0'

```

The answers chosen by this would then lead to the appropriate config files to be loaded. These files would then look something like

**simple_net.yaml**
```yaml
networks:
  network1:
    defined: true
  network2:
    defined: false
  network3:
    defined: false
```

**10.0.0.0.yaml**
```yaml
networks:
  network1:
    ip: "10.10.<%= node.group.index %>.<%= node.index.to_i + 100 %>"
    netmask: 255.255.224.0
    network: 10.10.0.0
    gateway: 10.10.0.1
  network2:
    ip: "10.10.<%= node.group.index.to_i + 32 %>.<%= node.index.to_i + 100 %>"
    netmask: 255.255.224.0
    network: 10.10.32.0
  network3:
    ip: "10.10.<%= node.group.index.to_i + 64 %>.<%= node.index.to_i + 100 %>"
    netmask: 255.255.224.0
    network: 10.10.64.0
```

Does this help clear up the idea I have in mind?
